language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: winrate-app
  api_key:
    secure: Oih3tucKRIJgORjTwx9Dj4k9R+cYrfBfFqkOSkS1pF5n6XBPegcA8hq75FuSNXTETIuJHmb4d6sEQ+Nb/bcIcmsGmoDnxe5QOIv27eHz9reK0XP0aEZe4QD8qL+828ToiL1fc1NaM9GmJUs+0vwgiYk1z2X/XKGJDSxyR26WetfxMjWLznaX+LDoF/HLRpse+0l0tYBLOa1EGmoqDEe7iw2zbTEYhCR04dUx1j/iY1rX58XbyKGtP0PJttwiTFtVrgBDQ9627WkzCQoLFApla3Hqf7DpPrpWmvEC56w5/OhF/2R2zZoRhxI3uHzUetVa6Eon8DgsT+bBGO01jxPehsU80EaLniS7ilyqSFT9Jzg7QxDFTPEtQAWqpsEnAPiNtEnvbpnTkwY0U6Tn6++O8PhMRLxDZRdyE77wR1/ErDPR2R3jMwEfcf4QBaC+QFdPPWJI2yyss7uoMNw2Q+mhcKoW6TJglOxzLsIbruwiYJOvhwZpZWv1ujtpa7zBOJHZxtN8c5XI1SvcLkIeT1UqSRGU3+bcXbu8+i4iX2Pj2OJOUdSHpDkAe6qrPzl3QLYN+v1Bl8KP331Sx4Cp3vSnS/19bIXDWyPiliQTe1UIJyFBERzh2pLh12L9aPWH3fV2xgSB7bQWVQkUsPD4UlTxDPmN6I4pjNYqG+kkXsGBwbY=
